### ISSUE TITLE
[버그 수정]: 시간이 잘못 계산되는 오류

### ISSUE THREAD

**Issue by NaamuKim** [boostcampwm-2022/web06-weview#363]
### 설명

![스크린샷 2022-12-08 오전 2 07 01](https://user-images.githubusercontent.com/83356118/206244373-7aedb0ae-4649-4806-bc7d-fd83efa62a2b.png)
### 🗒 체크리스트

- [x] 🔥 시간이 잘못 계산되는 오류가 있습니다.

**Comment by shyuuuuni** [comment]
FE에서 테스트하다보니 아래처럼 시간은 한국 시간인데 타임존은 UTC로 되어서 나오는 문제가 있음.

우석이형 도움으로 BE에서 로컬에서는 잘 저장하는데, 배포버전에서는 시간이 밀린다고 (아마 도커 컨테이너가 UTC라서?)

![Image](https://user-images.githubusercontent.com/63703962/206967652-04d5585f-3294-4367-8f98-88dc4bb7d54b.png)
